### ISSUE TITLE
Comments use a single "-" instead of "--"

### ISSUE THREAD

**Issue by Lucide** [agurodriguez/vscode-lbnf#2]
When using the defined commenting editor action, the extension adds a single "-" instead of "--".
BNFC for example does not recognize `- ...` as a comment.

In the screenshot in the extension description comments use `--` too:

![screenshot](https://github.com/agurod42/vscode-lbnf/raw/master/docs/screenshot.png)

Is there something wrong with my editor or can you reproduce?

**Comment by matpyz** [comment]
I have the same issue.

**Comment by matpyz** [comment]
@agurod42 Hi Agu! May I ask you to publish a new release with this latest change on VS Code marketplace? I don't think I know how to do this myself and perhaps I'm not even authorised to do this.
